---
version: '3.4'
services:
  weaviate-auth-okta-users:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8083'
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    ports:
      - 8083:8083
    restart: on-failure:0
    environment:
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_OIDC_ENABLED: 'true'
      AUTHENTICATION_OIDC_CLIENT_ID: '0oa7iz2g41rNxv95B5d7'
      AUTHENTICATION_OIDC_ISSUER: 'https://dev-32300990.okta.com/oauth2/aus7iz3tna3kckRWS5d7'
      AUTHENTICATION_OIDC_USERNAME_CLAIM: 'sub'
      AUTHENTICATION_OIDC_GROUPS_CLAIM: 'groups'
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'test@test.de'
      AUTHENTICATION_OIDC_SCOPES: 'openid,email'
      DISABLE_TELEMETRY: 'true'
...
